title: Brock Library Teaching Collection
subtitle: Open Access Lessons
author:
  name: GitHub User
  email: your-email@domain.com
description: > # this means to ignore newlines until "show_excerpts:"
  A public collection of teaching material by the Brock University Library Teaching and Learning department. 
baseurl: '/teaching-collection'

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: jekyllrb
    github:  jekyll
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# --------------------------------------------------------------
# COLLECTION SETTINGS
# --------------------------------------------------------------
# Wax leverages Jekyll collections for much of its
# functionality, therefor some of the keys below are from
# Jekyll while others are Wax-specific.
# For more info, refer to:
# ~> https://jekyllrb.com/docs/collections/

collections:
  exhibits:
    output: true
  qatar: # name of collection
    output: true # makes sure pages are output as html files
    layout: 'qatar_item' # the layout for the pages to use
    metadata:
      source: 'qatar.csv' # path to the metadata file within `_data`
    images:
      source: 'raw_images/qatar' # path to the directory of images within `_data`

# --------------------------------------------------------------
# SEARCH INDEX SETTINGS
# --------------------------------------------------------------
# You can create multiple search indexes below (though only one is
# recommended!) by specifying
# an `index` file to write it to and some `collections` for it to index
# and running `$ bundle exec rake wax:search` .

search:
  main:
    index: '/search/index.json' # file the index will get written to
    collections:
      qatar:
        content: true # whether or not to index page content
        fields: # the metadata fields to index
          - description
          - objective
          - label
          - discipline
          - object_type
          - creator
          - acrl
          - _date
          - license
          - study_status


# --------------------------------------------------------------
# SITE MENU SETTINGS
# --------------------------------------------------------------
# Each menu item needs a `label` (whats shown), and a `link`
# (where it goes). An item can optionally have a dropdown
# submenu via `sub`.

menu:
 # - label: 'Exhibits'
 #   sub:
 #     - label: 'Parallax Images'
 #       link: '/exhibits/parallax/'
 #     - label: 'Image References'
 #       link: '/exhibits/references/'
 #     - label: 'Subset Collection'
 #       link: '/exhibits/subset/'
  - label: 'New Stuff'
    link: '/blog/'
  - label: 'Browse'
    link: '/collection/'
  - label: 'Search'
    link: '/search/'
#  - label: 'How To'
#    link: '/learning/'
  - label: 'About'
    link: '/about/'
